title: Hidden Security Academy

plugins:
  - jekyll-assets
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num"

# ðŸ”¥ NOUVELLE CONFIGURATION pour https://hiddenacademy.github.io/
baseurl: ""  # <- Doit Ãªtre VIDE maintenant
url: "https://hiddenacademy.github.io"  # <- Nouvelle URL
